log:
  name: '20210916'
  version: 'test_1'
  log_graph: False

dataset:
  train_data: ["DIV2K", ]                                   # DIV2K, BSD500, ...
  test_data: ['Set5', 'Set14', 'BSD100', 'Urban100']        # ['Set5', 'Set14', 'BSD100', 'Urban100', 'Manga109']
  save_test_img: True
  test_only: True
  batch_size: 12
  shuffle: True
  num_workers: 16
  args:
    dir: "dataset"
    patch_size: 96
    scale: 2
    rgb_range: 1

model:
  net: 'HAN'
  pretrain: False       
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  n_colors: 3
  res_scale: 1

trainer:                        # pytorch lightning trainer options https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-flags           
  gpus: 1
  max_epochs: 250
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  log_gpu_memory: "all"
  #limit_val_batches: 0.5
  #profiler: "pytorch"
  #resume_from_checkpoint: "/logs/csnln_x2_epoch200_2/log_2110180842/checkpoints/epoch=53-step=6749.ckpt"
  #fast_dev_run: 1              

callback:
  save_top_k: 3
  earlly_stop_patience: 50
  min_delta: 1.0e-4

optimizer:
  name: 'adam'
  learning_rate: 1.0e-4
  weight_decay: 5.0e-2
  momentum: 0.9               # only work for SGD

scheduler:
  name: 'multistep'
  min_lr: 1.0e-8
  multistep: [50, 100, 150, 200, 250]   # work for MultiStepLR
  patience: 10                          # work for RedcueLROnPlateau
  cooldown: 5
  factor: 0.5                           # lr schedule decay factor
  