log:
  name: '20210916'
  version: 'test_1'
  log_graph: False

dataset:
  dir: "dataset/DIV2K"
  data: "div"                  # div, bad, zoom, zoomraw, zoompatcg
  scale_idx: [2, 3, 4]          
  patch_size: 64
  batch_size: 2
  shuffle: False
  num_workers: 4

model:
  net: 'NLST'                  # NLST or NLRN you can 
  in_channels: 3               # input image channel number, 3 for JPG, 4 for ARW
  work_channels: 128           # all the layer work on the same channel number
  filter_size: 64              # inpute filter size will be maintained along network 
  upsample: False
  iteration_steps: 12          # iteration step number should be same as the length of st_schedule
  mode: "embedded"             # 'gaussian', 'embedded'(dot), 'concatenate'
  st_schedule: "nnnnnnnnnnnn"  # 'a' means affine, 'h' for homography, 't' for tps
  tps_grid_size: 4

trainer:                       
  gpus: 1
  max_epochs: 200
  accumulate_grad_batches: 4
  gradient_clip_val: 0.5
  #profiler: "pytorch"
  #resume_from_checkpoint: "logs/adamW07_rgb01_v2/20210914/checkpoints/epoch=98-step=6236.ckpt"
  #fast_dev_run: 1             # This is for test - it will cause error for validation step

optimizer:
  learning_rate: 1.0e-5
  weight_decay: 1.0e-2
  patience: 5
