log:
  name: '20210916'
  version: 'test_1'
  log_graph: False

dataset:
  train_data: ['DIV2K']                 # DIV2K, Flickr2K, BSD500, ...
  test_data: ['Set5', 'Set14', 'BSD100', 'Urban100', ]                              # ['Set5', 'Set14', 'BSD100', 'Urban100', 'Manga109']
  save_test_img: True
  test_only: False
  batch_size: 6
  shuffle: True
  num_workers: 16
  args:
    dir: "dataset"
    patch_size: 96
    scale: 8
    rgb_range: 1                         # HAN, SwinIR pretrained as of 255, others as of 1

model:
  net: 'SCAN'
  pretrain: False
  loss: 'l1'       

trainer:                                 # pytorch lightning trainer options https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-flags           
  gpus: 1
  max_epochs: 550
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  log_gpu_memory: "all"
  #limit_val_batches: 0.5
  #profiler: "pytorch"
  #resume_from_checkpoint: 'logs/scan_x2_test/log_2112072051/checkpoints/epoch=509-step=34169.ckpt'
  #fast_dev_run: 1              

callback:
  save_top_k: 10
  earlly_stop_patience: 300
  min_delta: 1.0e-4

optimizer:
  name: 'adamw'
  learning_rate: 1.0e-4
  weight_decay: 5.0e-3
  momentum: 0.9                         # only work for SGD

scheduler:
  name: 'multistep'
  min_lr: 1.0e-8
  multistep: [250, 450, 500]   # work for MultiStepLR
  patience: 5                          # work for RedcueLROnPlateau
  cooldown: 5
  period: 8
  factor: 0.1                           # lr schedule decay factor
  