log:
  name: '20210831'
  version: 'test_1'

dataset:
  dir_data: "dataset/SRRAW"
  get_from_dir: "onlycrop"     # onlycrop / cropped / aligned
  img_ext: "JPG"               # ARW / JPG / ...
  scale_idx: [1, 2]            # scale index (ex. 00001, 00002, 00003). First will be ref(target) 
  patch_size: -1               # -1 for full size image (no crop)
  raw_image: False             # if True, belowing in_channel param sould be 4

dataloader:
  batch_size: 2
  shuffle: True
  num_workers: 4

model:
  output_theta: 6 
  size: 1024
  feature_extraction_last_layer: ''
  return_correlation: False
  fr_channels: [225, 128, 64, 32]
  feature_self_matching: False
  normalize_features: True
  normalize_matches: True
  batch_normalization: True
  train_fe: False
  matching_type: 'correlation'

trainer:                       # TODO main trainer lightning module params
  gpus: 1
  max_epochs: 1
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 1
  gradient_clip_val: 0.5
  log_every_n_steps: 10
